import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

// Everything the viewer needs that the tile build computed. Persisted as
// meta.json next to the tiles so index.html can be regenerated on its own.
export type MapMeta = {
  maxZoom: number; // highest native zoom level (one native pixel == one block)
  minX: number; // world block X of native pixel column 0
  minZ: number; // world block Z of native pixel row 0
  tileSize: number; // Leaflet tileSize (px); one base tile == one region (512)
  spawn: { x: number; z: number } | null;
  dimension?: string;
  // Minecraft version the world reports (from level.dat), and the version this
  // renderer's block list / color tables were built for. A mismatch means the
  // colors may be stale.
  version?: { name: string | null; dataVersion: number | null } | null;
  targetVersion?: { name: string; dataVersion: number };
  biomeSuper?: number; // regions per biome super-tile side (GridLayer tile size)
};

export function indexHtml(meta: MapMeta): string {
  const { maxZoom, minX, minZ, tileSize, spawn } = meta;
  const biomeTile = tileSize * (meta.biomeSuper ?? 1); // GridLayer tile = 1 biome super-tile
  const initialZoom = Math.max(0, maxZoom - 2);
  const title = meta.dimension ? `${meta.dimension} map` : 'Dimension map';
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title}</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
  html,body,#map{height:100%;margin:0;background:#0b0b0b}
  /* keep block-pixels crisp when zoomed past native zoom (no smoothing) */
  .leaflet-tile{image-rendering:pixelated;image-rendering:-moz-crisp-edges;image-rendering:crisp-edges}
  .coord{background:rgba(0,0,0,.6);color:#eee;font:12px/1.4 monospace;padding:4px 8px;border-radius:4px}
  /* biome polygons are invisible but must still catch the cursor */
  .biome-region{pointer-events:all}
</style>
</head>
<body>
<div id="map"></div>
<script>
  var MAXZOOM = ${maxZoom};
  var MINX = ${minX};     // world block X of native pixel column 0
  var MINZ = ${minZ};     // world block Z of native pixel row 0
  var SPAWN = ${spawn ? JSON.stringify(spawn) : 'null'};

  var map = L.map('map', { crs: L.CRS.Simple, minZoom: 0, maxZoom: MAXZOOM + 2 });

  L.tileLayer('tiles/{z}/{x}/{y}.png', {
    attribution: 'Map generated by <a href="https://github.com/FreekBes/fmcmapper" target="_blank">fmcmapper</a>',
    tileSize: ${tileSize},
    minZoom: 0,
    maxZoom: MAXZOOM + 2,    // a couple of upscaled over-zoom steps
    maxNativeZoom: MAXZOOM,
    minNativeZoom: 0,
    noWrap: true
  }).addTo(map);

  // latlng -> Minecraft block coords (native pixel == world block at MAXZOOM)
  function toBlock(latlng) {
    var p = map.project(latlng, MAXZOOM);
    return { x: Math.floor(MINX + p.x), z: Math.floor(MINZ + p.y) };
  }
  // Minecraft block coords -> latlng
  function fromBlock(x, z) {
    return map.unproject(L.point(x - MINX, z - MINZ), MAXZOOM);
  }

  var Coords = L.Control.extend({
    options: { position: 'bottomleft' },
    onAdd: function () {
      var d = L.DomUtil.create('div', 'coord');
      d.textContent = 'move the cursor';
      this._d = d;
      this._x = null; this._z = null; this._b = '';
      return d;
    },
    pos: function (x, z) { this._x = x; this._z = z; this._render(); },
    biome: function (b) { this._b = b; this._render(); },
    _render: function () {
      if (this._x === null) return;
      var t = 'X ' + this._x + '   Z ' + this._z;
      if (this._b) t += '   •   ' + this._b;
      this._d.textContent = t;
    }
  });
  var coords = new Coords();
  map.addControl(coords);
  map.on('mousemove', function (e) { var b = toBlock(e.latlng); coords.pos(b.x, b.z); });

  // Biome overlay: invisible interactive polygons that report the biome on hover.
  // Regions are grouped into super-tiles, one GeoJSON each (biomes/<sx>_<sy>.geojson).
  // Pinning a GridLayer to the native zoom with a super-tile-sized tile makes each
  // tile coordinate equal a super-tile, so Leaflet's own tile lifecycle loads the
  // ones in view and unloads (frees) them as you pan. index.json lists which exist.
  function prettyBiome(id) {
    return id.replace(/^[^:]*:/, '').replace(/_/g, ' ').replace(/\\b\\w/g, function (c) { return c.toUpperCase(); });
  }
  var biomeStyle = { stroke: false, fill: true, fillOpacity: 0, fillColor: '#ffffff', className: 'biome-region' };
  function onEachBiome(f, lyr) {
    var name = prettyBiome(f.properties.biome);
    lyr.on('mouseover', function () { coords.biome(name); });
    lyr.on('mouseout', function () { coords.biome(''); });
  }

  var biomeGroup = L.layerGroup().addTo(map);
  var biomeAvail = null; // "tx_ty" -> true (exists on disk)
  var biomeCache = {};   // "tx_ty" -> L.geoJSON (parsed once, re-shown on revisit)
  function showRegion(id) {
    if (biomeCache[id]) {
      if (!biomeGroup.hasLayer(biomeCache[id])) biomeGroup.addLayer(biomeCache[id]);
      return;
    }
    var layer = L.geoJSON(null, { style: biomeStyle, onEachFeature: onEachBiome });
    biomeCache[id] = layer;
    biomeGroup.addLayer(layer);
    fetch('biomes/' + id + '.geojson').then(function (r) { return r.ok ? r.json() : null; })
      .then(function (gj) { if (gj && gj.features) layer.addData(gj); }).catch(function () { /* skip */ });
  }
  function hideRegion(id) {
    if (biomeCache[id] && biomeGroup.hasLayer(biomeCache[id])) biomeGroup.removeLayer(biomeCache[id]);
  }

  var BiomeGrid = L.GridLayer.extend({
    createTile: function (coords, done) {
      var tile = document.createElement('div'); // invisible placeholder; data lives in biomeGroup
      var id = coords.x + '_' + coords.y;
      if (biomeAvail && biomeAvail[id]) showRegion(id);
      setTimeout(function () { done(null, tile); }, 0);
      return tile;
    }
  });
  // Pinned to the native zoom -> each tile coord is one biome super-tile.
  var biomeGrid = new BiomeGrid({ tileSize: ${biomeTile}, minNativeZoom: MAXZOOM, maxNativeZoom: MAXZOOM, noWrap: true });
  biomeGrid.on('tileunload', function (e) { hideRegion(e.coords.x + '_' + e.coords.y); });
  fetch('biomes/index.json').then(function (r) { return r.ok ? r.json() : []; }).then(function (ids) {
    biomeAvail = {};
    ids.forEach(function (id) { biomeAvail[id] = true; });
    biomeGrid.addTo(map); // start the tile lifecycle once we know what exists
  }).catch(function () { /* no biome data */ });

  if (SPAWN) {
    var c = fromBlock(SPAWN.x, SPAWN.z);
    map.setView(c, ${initialZoom});
    L.circleMarker(c, { radius: 5, weight: 2, color: '#fff', fillColor: '#e33', fillOpacity: 1 })
      .addTo(map)
      .bindTooltip('Spawn (' + SPAWN.x + ', ' + SPAWN.z + ')');
  } else {
    map.setView([0, 0], 0);
  }
</script>
</body>
</html>
`;
}

// Write index.html into outDir. Uses the passed meta, or reads outDir/meta.json.
export function writeViewer(outDir: string, meta?: MapMeta): void {
  const m = meta ?? (JSON.parse(readFileSync(join(outDir, 'meta.json'), 'utf8')) as MapMeta);
  writeFileSync(join(outDir, 'index.html'), indexHtml(m));
}

// Standalone CLI: regenerate index.html from an existing tile build's meta.json.
//   node build/viewer.js [outDir]   (or OUTPUT_PATH=... node build/viewer.js)
// outDir comes from the positional arg, falling back to env, then a default —
// matching buildtiles.js so both tools take the same inputs.
if (require.main === module) {
  const outDir = process.argv[2] ?? process.env.OUTPUT_PATH ?? './output';
  writeViewer(outDir);
  console.log(`wrote ${join(outDir, 'index.html')} from ${join(outDir, 'meta.json')}`);
}
